### ISSUE TITLE
Forbidden (403)

### ISSUE THREAD

**Issue by tonhou** [mkb79/audible-cli#127]
I have been using for a month or more without issue or more but now have this:

./audible library list
Uncaught Exception
Traceback (most recent call last):
  File "audible_cli/cli.py", line 60, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "audible_cli/decorators.py", line 25, in wrapper
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 642, in run_until_complete
  File "audible_cli/decorators.py", line 63, in wrapper
  File "audible_cli/cmds/cmd_library.py", line 189, in list_library
  File "audible_cli/cmds/cmd_library.py", line 31, in _get_library
  File "audible_cli/models.py", line 561, in from_api_full_sync
  File "audible_cli/models.py", line 535, in from_api
  File "audible/client.py", line 348, in _request
  File "audible_cli/utils.py", line 73, in full_response_callback
  File "audible/client.py", line 39, in raise_for_status
audible.exceptions.Unauthorized: Forbidden (403): Request could not be authenticated

Can you provide some direction? Many thanks.

**Comment by mkb79** [comment]
It seams that your authentication data are not valid for the request. This can have different reasons. 

Some questions from me:
1. Which command you are running?
2. Do you have changed your Audible Abo
3. Do you have removed some Audible devices on the Amazon webpage?

**Comment by tonhou** [comment]
Thanks for comments.
Hmm .... could a Audible password change be a cause?
If so how could it be re-set with audible-cli?

**Comment by mkb79** [comment]
A password change should not be the reason for this! So you can run `audible manage auth-file remove` and then `audible manage auth-file add`. Make sure the name of the new auth file is the same as the old.

**Comment by tonhou** [comment]
I don't recall the name of the present auth file, can I find that out?

**Comment by mkb79** [comment]
Run `audible manage config edit`. This will open the config file and show you the profile name and auth file name. Otherwise you can take a look to your [App dir](https://github.com/mkb79/audible-cli#app-dir) where the file is saved.

**Comment by tonhou** [comment]
Thanks, found the name but attempting to remove:

./audible manage auth-file remove
Please enter name for the auth file: tonhou.json
Uncaught Exception
Traceback (most recent call last):
  File "audible_cli/cli.py", line 60, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "audible_cli/cmds/cmd_manage.py", line 219, in remove_auth_file
  File "audible/auth.py", line 692, in refresh_access_token
  File "audible/auth.py", line 66, in refresh_access_token
  File "httpx/_models.py", line 736, in raise_for_status
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.amazon.com.au/auth/token'
For more information check: https://httpstatuses.com/400

**Comment by mkb79** [comment]
Yeah all okay. It seams that your auth file was not valid anymore. So a remove (include deregistration) failed. Make sure that the auth file is removed now from app dir before proceed. Otherwise delete them now manually (deregistration is not possible)!

**Comment by tonhou** [comment]
So is it necessary to re-run audible quickstart?

**Comment by mkb79** [comment]
It’s not necessary and it will not work. The `quickstart` only work if there is no config file present.

**Comment by tonhou** [comment]
Thank you all is well now.
I had also deleted the config file (think I misunderstood!).
So I ran quickstart and re-set up.

Now working correctly, thank you for your patience and help.

**Comment by mkb79** [comment]
Good to hear that. The quickstart command creates a initial config and your first profile including an auth file. So this is fine. I will close this now as completed.
