### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by markus681** [mkb79/audible-cli#17]
Hello, i found this Repo and find it really great, but can't login.
As you can see in the log i use Python3.7 on Debian10. 64bit PC
please help, i like the programm...

```markus@bigeddy ~> audible-quickstart
Welcome to the audible 0.5.4 quickstart utility.
================================================

Quickstart will guide you through the process of build a basic 
config, create a first profile and assign an auth file to the profile now.

The profile created by quickstart will set as primary. It will be used, if no 
other profile is chosen.

An auth file can be shared between multiple profiles. Simply enter the name of 
an existing auth file when asked about it. Auth files have to be stored in the 
config dir. If the auth file doesn't exists, it will be created. In this case, 
an authentication to the audible server is necessary to register a new device.

Selected dir to proceed with:
/home/markus/.audible

Please enter values for the following settings (just press Enter to accept a default value, if one is given in brackets).

Please enter a name for your primary profile [audible]: 

Enter a country code for the profile: de

Please enter a name for the auth file [audible.json]: 

Do you want to encrypt the auth file? [y/N]: n

Please enter your amazon username: ********@yahoo.de
Please enter your amazon password: 
Repeat for confirmation: 

+--------------------+----------------------------+
| Option             | Value                      |
+--------------------+----------------------------+
| profile_name       | audible                    |
| auth_file          | audible.json               |
| country_code       | de                         |
| auth_file_password | -                          |
| audible_username   | ********@yahoo.de |
| audible_password   | ***                        |
+--------------------+----------------------------+
Do you want to continue? [y/N]: y

Login with amazon to your audible account now.
Captcha found
Open Captcha with default image viewer [Y/n]: n
Please open the following url with a webbrowser to get the captcha:
https://opfcaptcha-prod.s3.amazonaws.com/799c8982e5134f9c84d65c15aba1ccca.gif?
Answer for CAPTCHA: tTqzCx
Captcha found
Open Captcha with default image viewer [Y/n]: n
Please open the following url with a webbrowser to get the captcha:
https://opfcaptcha-prod.s3.amazonaws.com/e721e3a403a8418b99af415042718dc9.gif?
Answer for CAPTCHA: smzwtD
Traceback (most recent call last):
  File "/usr/local/bin/audible-quickstart", line 11, in <module>
    load_entry_point('audible-cli==0.0.dev15', 'console_scripts', 'audible-quickstart')()
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/audible_cli/cli.py", line 47, in quickstart
    sys.exit(ctx.forward(cmd_quickstart.cli))
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 628, in forward
    return self.invoke(cmd, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/markus/.local/lib/python3.7/site-packages/audible_cli/cmds/cmd_quickstart.py", line 153, in cli
    file_password=d.get("auth_file_password")
  File "/home/markus/.local/lib/python3.7/site-packages/audible_cli/utils.py", line 65, in build_auth_file
    otp_callback=prompt_otp_callback)
  File "/home/markus/.local/lib/python3.7/site-packages/audible/auth.py", line 365, in from_login
    approval_callback=approval_callback)
  File "/home/markus/.local/lib/python3.7/site-packages/audible/auth.py", line 594, in re_login
    approval_callback=approval_callback)
  File "/home/markus/.local/lib/python3.7/site-packages/audible/login.py", line 393, in login
    raise Exception("Unable to login")
Exception: Unable to login
```

Greetz Markus

**Comment by markus681** [comment]
allright i got it to work, first i had to add a mobil number, activate 2FA then i deactivated the 2FA and then it worked...
Great Job!!!

Greetz Markus

**Comment by mkb79** [comment]
Hi, it‘s great to hear that you could solve your problem! 

If you find another issue, feel free to contact me again!

**Comment by NeoCortex97** [comment]
I cannot login, despite having 2FA deactivatedalready

**Comment by mkb79** [comment]
I‘ve updated audible-cli now. You can now login with  external browser to proceed.

**Comment by joshunger** [comment]
@mkb79 awesome thanks for adding an external browser! I wonder if it would be helpful to add an OTP section to the readme?

**Comment by mkb79** [comment]
Hi. Which information you want to read about in the README?

**Comment by joshunger** [comment]
👋 how about something like?

## OTP
If you have enabled Two-Factor authentication and you receive an OTP trying to log in, re-run `audible quickstart` and answer Yes to `Do you want to login with external browser?`.

Is there a callback that can be implemented to support this from the command line?
