### ISSUE TITLE
FR: library data download

### ISSUE THREAD

**Issue by lorensr** [mkb79/audible-cli#2]
Nice tool! It would be nice to be able to download a list of all books in my library, along with info about each book, like genre, whether I've completed it, etc ☺️

**Comment by mkb79** [comment]
That’s not a problem. I can implement this. Which infos you need at least? What output format did you think of (csv, json, ...)?

**Comment by lorensr** [comment]
Awesome! CSV. I'm looking for:

ID (eg B07NNYBKXF)
Title
Subtitle
Author
Narrated by
Series
Length
Finished (boolean)

**Comment by mkb79** [comment]
I‘ve add a command to export the library to a csv file to this [branch](https://github.com/mkb79/audible-cli/tree/issue-2).

Before I optimize the code can you tell me if this is running on your machine?!

Run with `audible library export -o FILENAME`

**Comment by lorensr** [comment]
This is perfect! Worked great, thanks so much ☺️

![image](https://user-images.githubusercontent.com/251288/93708607-9f0c1980-fb05-11ea-956f-eef7d4cbc392.png)

**Comment by lorensr** [comment]
It only has 100 books—is the API paginated, can you get all of them? 😄

**Comment by mkb79** [comment]
I‘ve added `num_results=1000` to api call. Can you test again please?!

**Comment by lorensr** [comment]
Tried twice, both times got:

```
audible-cli git:(𝘮 ← 2 issue-2) 2A $ audible library export -o test.tsv
Traceback (most recent call last):
  File "/usr/local/bin/audible", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/audible_cli/cli.py", line 108, in main
    cli(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/audible_cli/cmd_library.py", line 67, in export_library
    loop.run_until_complete(_export_library(config.auth, **params))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/audible_cli/cmd_library.py", line 42, in _export_library
    item_data[x] = ", ".join([y["name"] for y in v])
TypeError: 'NoneType' object is not iterable
```

**Comment by lorensr** [comment]
Actually, looks like it worked! Almost perfectly—Audible app says I have 530 titles, and there are 529 rows

**Comment by lorensr** [comment]
Is there a date purchased / added to library?

**Comment by lorensr** [comment]
Cover image URL

**Comment by lorensr** [comment]
date finished, date started, date released, genre? 😄

I can construct a link to the book webpage with `https://www.audible.com/pd/<asin>`

**Comment by mkb79** [comment]
I’ve added some data to export. I can’t find date finished and date started. So this data can’t be exported.

**Comment by lorensr** [comment]
Thanks again 🤗 

![image](https://user-images.githubusercontent.com/251288/93744939-a2b0a680-fbc0-11ea-9cf5-b55fdbe55a21.png)

![image](https://user-images.githubusercontent.com/251288/93744962-ad6b3b80-fbc0-11ea-8188-fee939cb1984.png)

**Comment by mkb79** [comment]
You have make subtables. Not bad. Maybe I could export the data in a sql database?! 

If everything else okay with the code? I would vmcreate a pr then.

**Comment by lorensr** [comment]
Was easy, Airtable does it mostly automatically.

Yep, sounds good ☺️

**Comment by mkb79** [comment]
I‘ve created a pr now. If someone has special wishes for the library export command is welcome to participate.
