### ISSUE TITLE
Quickstart error

### ISSUE THREAD

**Issue by elahn** [mkb79/audible-cli#40]
Using master:

```
# audible-quickstart
Traceback (most recent call last):
  File "/home/elahn/.local/bin/audible-quickstart", line 8, in <module>
    sys.exit(quickstart())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/elahn/.local/lib/python3.6/site-packages/audible_cli/cli.py", line 47, in quickstart
    sys.exit(ctx.forward(cmd_quickstart.cli))
  File "/usr/lib/python3/dist-packages/click/core.py", line 553, in forward
    return self.invoke(cmd, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: cli() missing 1 required positional argument: 'ctx'
```

**Comment by mkb79** [comment]
That's strange. Which version of audible-cli and click you use? Can you try `audible quickstart` command (without dash)!

**Comment by elahn** [comment]
I'm using the master branch from this repo. I also tried the one on linuxbrew with the same result. Sorry about the delay, for some reason I didn't get a notification.

```
# audible quickstart
Traceback (most recent call last):
  File "/home/elahn/.local/bin/audible", line 8, in <module>
    sys.exit(main())
  File "/home/elahn/.local/lib/python3.6/site-packages/audible_cli/cli.py", line 54, in main
    sys.exit(cli(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: cli() missing 1 required positional argument: 'ctx'
```

**Comment by elahn** [comment]
`python3-click/bionic,bionic,now 6.7-3 all [installed,automatic]`

**Comment by mkb79** [comment]
Can you try to update click to >=7.x. I use click 7.x as I wrote audible-cli. Maybe there are some issues to previous versions of click.

**Comment by elahn** [comment]
Thank you, a simple `pip install -U click` fixed it.
