### ISSUE TITLE
Export fails when a book has no cover (i.e. empty product_images)

### ISSUE THREAD

**Issue by MickeyDance** [mkb79/audible-cli#46]
When a book doesn't have an image then the product_images field is set to an empty hash. In line 98 of cmd_library.py the cover_url field is set via v["500"] which doesn't exist as a key causing the export to fail.
I fixed this (in my case) by changing those lines to:
                elif key == "product_images":
                    if '500' in v:
                        data_row["cover_url"] = v["500"]
                    else:
                        print('No cover URL for:', item['title'])
You can reproduce this on audible.co.uk via the following URL: 
https://www.audible.co.uk/search?keywords=Earth+Unrelenting&ref=a_pd_No-Pla_t1_header_search
which (obviously) is for a book called Earth Unreleting by M. R. Forbes

Traceback is:

audible library export -t 600 -o myexport
Traceback (most recent call last):
  File "/usr/local/bin/audible", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/audible_cli/cli.py", line 54, in main
    sys.exit(cli(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/audible_cli/cmds/cmd_library.py", line 129, in export_library
    loop.run_until_complete(_export_library(session.auth, **params))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/audible_cli/cmds/cmd_library.py", line 98, in _export_library
    data_row["cover_url"] = v["500"]
KeyError: '500'

**Comment by MickeyDance** [comment]
PS Thsi is quite rare as for the 927 audible books I have bought that's the only one with this problem.

**Comment by mkb79** [comment]
Thank your for this information. Fixed this.

**Comment by MickeyDance** [comment]
Thanks for the speedy reponse.
